### ISSUE TITLE
Update to support terraform 0.12

### ISSUE THREAD

**Issue by bfin** [FairwindsOps/terraform-vpc#46]
Major release (https://www.terraform.io/upgrade-guides/0-12.html)

**Comment by bambash** [comment]
Hi @bfin - Terraform 0.12 is now supported. If you run into any problems, feel free to open another issue!

https://github.com/FairwindsOps/terraform-vpc/releases/tag/5.0.0

**Comment by bfin** [comment]
Thanks for the update @bambash !
